[package]
name = "chatterbox-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
[dependencies.pyo3]
version = "0.28.0"
# Enabling this cargo feature will cause PyO3 to start a Python interpreter on first call to `Python::attach`
features = ["auto-initialize"]
